name: Deploy Infrastructure and Process Images on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy_and_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package Lambda Functions
        run: |
          # Create zip files for Lambda functions
          zip -r lambda/beta.zip lambda/beta/
          zip -r lambda/prod.zip lambda/prod/

      - name: Upload Lambda Function Code to S3
        run: |
          # Upload the zip files to the S3 bucket
          aws s3 cp lambda/beta.zip s3://${{ secrets.S3LAMBDABUCKET }}/acmelabs-imageanalyzer/beta.zip
          aws s3 cp lambda/prod.zip s3://${{ secrets.S3LAMBDABUCKET }}/acmelabs-imageanalyzer/prod.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          # Deploy the CloudFormation stack
          aws cloudformation deploy \
            --template-file cloudformation/template.yaml \
            --stack-name AcmeLabsImageAnalyzerStack \
            --parameter-overrides \
              S3LambdaBucket=${{ secrets.S3LAMBDABUCKET }} \
              S3ImageAnalyzerBucket=${{ secrets.S3IMAGEANALYZERBUCKET }} \
              BetaDynamoDBTableName=${{ secrets.BETADYNAMODBTABLENAME }} \
              ProdDynamoDBTableName=${{ secrets.PRODDYNAMODBTABLENAME }} \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Upload Images to S3
        run: |
          # Upload images to the S3 bucket for processing
          aws s3 cp images/ rekognition-input/prod/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
